### ISSUE TITLE
deluged:builtins.KeyError: 'disk.num_blocks_cache_hits'

### ISSUE THREAD

**Issue by iamydp** [amefs/quickbox-lite#166]
```
builtins.KeyError: 'disk.num_blocks_cache_hits'
Sep  4 00:00:40 Nass deluged[993989]: 00:00:40 [CRITICAL][twisted                       :147 ] Unhandled Error
Sep  4 00:00:40 Nass deluged[993989]: Traceback (most recent call last):
Sep  4 00:00:40 Nass deluged[993989]:   File "/usr/lib/python3/dist-packages/deluge/core/daemon_entry.py", line 122, in run_daemon
Sep  4 00:00:40 Nass deluged[993989]:     daemon.start()
Sep  4 00:00:40 Nass deluged[993989]:   File "/usr/lib/python3/dist-packages/deluge/core/daemon.py", line 164, in start
Sep  4 00:00:40 Nass deluged[993989]:     reactor.run()
Sep  4 00:00:40 Nass deluged[993989]:   File "/usr/local/lib/python3.10/dist-packages/twisted/internet/base.py", line 1315, in run
Sep  4 00:00:40 Nass deluged[993989]:     self.mainLoop()
Sep  4 00:00:40 Nass deluged[993989]:   File "/usr/local/lib/python3.10/dist-packages/twisted/internet/base.py", line 1325, in mainLoop
Sep  4 00:00:40 Nass deluged[993989]:     reactorBaseSelf.runUntilCurrent()
Sep  4 00:00:40 Nass deluged[993989]: --- <exception caught here> ---
Sep  4 00:00:40 Nass deluged[993989]:   File "/usr/local/lib/python3.10/dist-packages/twisted/internet/base.py", line 991, in runUntilCurrent
Sep  4 00:00:40 Nass deluged[993989]:     call.func(*call.args, **call.kw)
Sep  4 00:00:40 Nass deluged[993989]:   File "/usr/lib/python3/dist-packages/deluge/core/core.py", line 345, in _on_alert_session_stats
Sep  4 00:00:40 Nass deluged[993989]:     self._update_session_cache_hit_ratio()
Sep  4 00:00:40 Nass deluged[993989]:   File "/usr/lib/python3/dist-packages/deluge/core/core.py", line 361, in _update_session_cache_hit_ratio
Sep  4 00:00:40 Nass deluged[993989]:     self.session_status['disk.num_blocks_cache_hits'] / blocks_read
Sep  4 00:00:40 Nass deluged[993989]: builtins.KeyError: 'disk.num_blocks_cache_hits'
Sep  4 00:00:40 Nass deluged[993989]: Unhandled Error
Sep  4 00:00:40 Nass deluged[993989]: Traceback (most recent call last):
Sep  4 00:00:40 Nass deluged[993989]:   File "/usr/lib/python3/dist-packages/deluge/core/daemon_entry.py", line 122, in run_daemon
Sep  4 00:00:40 Nass deluged[993989]:     daemon.start()
Sep  4 00:00:40 Nass deluged[993989]:   File "/usr/lib/python3/dist-packages/deluge/core/daemon.py", line 164, in start
Sep  4 00:00:40 Nass deluged[993989]:     reactor.run()
Sep  4 00:00:40 Nass deluged[993989]:   File "/usr/local/lib/python3.10/dist-packages/twisted/internet/base.py", line 1315, in run
Sep  4 00:00:40 Nass deluged[993989]:     self.mainLoop()
Sep  4 00:00:40 Nass deluged[993989]:   File "/usr/local/lib/python3.10/dist-packages/twisted/internet/base.py", line 1325, in mainLoop
Sep  4 00:00:40 Nass deluged[993989]:     reactorBaseSelf.runUntilCurrent()
Sep  4 00:00:40 Nass deluged[993989]: --- <exception caught here> ---
Sep  4 00:00:40 Nass deluged[993989]:   File "/usr/local/lib/python3.10/dist-packages/twisted/internet/base.py", line 991, in runUntilCurrent
Sep  4 00:00:40 Nass deluged[993989]:     call.func(*call.args, **call.kw)
Sep  4 00:00:40 Nass deluged[993989]:   File "/usr/lib/python3/dist-packages/deluge/core/core.py", line 345, in _on_alert_session_stats
Sep  4 00:00:40 Nass deluged[993989]:     self._update_session_cache_hit_ratio()
Sep  4 00:00:40 Nass deluged[993989]:   File "/usr/lib/python3/dist-packages/deluge/core/core.py", line 361, in _update_session_cache_hit_ratio
Sep  4 00:00:40 Nass deluged[993989]:     self.session_status['disk.num_blocks_cache_hits'] / blocks_read
Sep  4 00:00:40 Nass deluged[993989]: builtins.KeyError: 'disk.num_blocks_cache_hits'

```
/var/log/syslog摘抄如上,我使用傲腾做系统盘,根目录只给了11g,现在已经被log占满了

**Comment by iamydp** [comment]
附:[相关commit](https://github.com/deluge-torrent/deluge/commit/89189adb24321c3db6bfa816ec557d7d8367ba24)

**Comment by amefs** [comment]
你是使用了libtorrent 2.0.x？
目前临时解决方案：
1. 停止 `deluged` 服务
2. 按照你给的 commit 修改 `nano /usr/lib/python3/dist-packages/deluge/core/core.py`
3. 运行 `python3 -m compileall /usr/lib/python3/dist-packages/deluge/core/core.py`
4. 重启 `deluged` 服务

**Comment by thekingisherenow** [comment]
same error.

**Comment by amefs** [comment]
please check the Libtorrent version: `dpkg -l | grep libtorrent`.
