### ISSUE TITLE
面板突然502打不开了

### ISSUE THREAD

**Issue by 9191521** [amefs/quickbox-lite#200]
**描述 Bug**
之前都正常使用，今天装了rclone和alist两个软件，再打开网页面板就502了，其他软件正常。
把rclone跟alist卸载，执行box update quickbox, 就卡住了，删除lock再次执行还是卡住了，现在面板打不开。
Nginx 显示正常
80/443端口也没被占用

**重现 Bug**
（之前安装新版本python3，误删过usr/bin/下的python3，新建文件用ln命令链接到了新装的python3）
> box update quickbox
Traceback (most recent call last):
  File "/usr/bin/lsb_release", line 25, in <module>
    import lsb_release
ModuleNotFoundError: No module named 'lsb_release'
Traceback (most recent call last):
  File "/usr/bin/lsb_release", line 25, in <module>
    import lsb_release
ModuleNotFoundError: No module named 'lsb_release'
➜ Checking and performing updates to system... 
✓ System updated.
➜ Updating QuickBox local repository...
✓ QuickBox local repository updated
➜ Adjust file permission...
✓ file permission updated
➜ Updating bashrc...
✓ bashrc updated
➜ Updating skel...
✓ skel updated
➜ Updating QuickBox service...
➜ Upgrade nodejs to v14
➜ Reconfig Dashboard service...
✓ Dashboard service updated
➜ ttyd current version: 1.7.3, latest version: 1.7.3
➜ Updating QuickBox dashboard...

troubleshoot 也卡住了

> box troubleshoot
   This script will help you generate a
    compressed file contains all        
    necessary debug infos.              

   ✓ General system info generated

**桌面系统 (请填写下列信息):**
window10 chrome

Ubuntu 18.04  OP的小鸡

**Comment by 9191521** [comment]
重启好了
