### ISSUE TITLE
App install not working from dashboard (Deb12)

### ISSUE THREAD

**Issue by Velenski** [amefs/quickbox-lite#214]
**Describe the bug**
When clicking the install button on the dashboard nothing happens.
this goes for all packages, the screen popsup but it stays blank and nothing happens.

I have tried different machines and browsers to reproduce and all same result.
Using Debian 12 on a hetzner VM with AMD Ryzen CPU (4 cores)
I reinstalled the VM but that did not give a different result.
No browser plugins that could have effect.

Windows 11
Browsers: Edge Chromium, Chrome, Firefox

**Comment by tautcony** [comment]
Please check the log file located at `/srv/dashboard/db/output.log` for execution details and post any error info for further debugging.

**Comment by Velenski** [comment]
> Please check the log file located at `/srv/dashboard/db/output.log` for execution details and post any error info for further debugging.

there is nothing refering to the problem in that log it only shows rtorrent install from the initial box setup/install

[output.log](https://github.com/amefs/quickbox-lite/files/13810453/output.log)

**Comment by tautcony** [comment]
Are there any errors in the `/root/quickbox.*.log' log file during Quickbox-Lite setup, especially when installing the dashboard?

If the network and boot time are displayed correctly, it should have been installed successfully. then it's possible that the command has not been sent to the server correctly, you can check if there is an error printed in the browser F12.

**Comment by Velenski** [comment]
when i try installing emby as example and use F12 it gives a 502 bad gateway error. in the dev console.

ws/socket.io/?EIO=4&transport=polling&t=OpBCOHy    that is the error shown

![image](https://github.com/amefs/quickbox-lite/assets/54041984/50c1d58f-627d-477f-a318-50010981e764)

**Comment by tautcony** [comment]
Check the service with `systemctl status quickbox-ws', you can try restarting the service with `systemctl restart quickbox-ws'.

**Comment by Velenski** [comment]
tried to restart it but getting the same result from the status:

● quickbox-ws.service - QuickBox Status Update WebSocket Interface
     Loaded: loaded (/etc/systemd/system/quickbox-ws.service; enabled; preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Wed 2024-01-03 20:36:39 CET; 17s ago
    Process: 91098 ExecStart=/usr/bin/node /srv/dashboard/ws/dist/server.js (code=exited, status=1/FAILURE)
   Main PID: 91098 (code=exited, status=1/FAILURE)
        CPU: 101ms

**Comment by tautcony** [comment]
Try to start the service directly with the command `/usr/bin/node /srv/dashboard/ws/dist/server.js`, failure reason may be displayed.

**Comment by Popol069** [comment]
Hello,
I have the same issue. I installed version 1.5.9 from scratch :

```
/usr/bin/node /srv/dashboard/ws/dist/server.js
node:internal/modules/cjs/loader:1137
  throw err;
  ^

Error: Cannot find module 'express'
Require stack:
- /srv/dashboard/ws/dist/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at 860 (/srv/dashboard/ws/dist/server.js:1:5447)
    at o (/srv/dashboard/ws/dist/server.js:1:5819)
    at /srv/dashboard/ws/dist/server.js:1:5873
    at /srv/dashboard/ws/dist/server.js:1:6359
    at Object.<anonymous> (/srv/dashboard/ws/dist/server.js:1:6363)
    at Module._compile (node:internal/modules/cjs/loader:1356:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/srv/dashboard/ws/dist/server.js' ]
}

Node.js v18.19.0
```

**Comment by Velenski** [comment]
i am getting near same results as described above.

**Comment by tautcony** [comment]
Reinstall dependencies by following command

```shell
cd /srv/dashboard/ws/
npm ci --production
# check result
/usr/bin/node /srv/dashboard/ws/dist/server.js
# if start successfully
systemctl restart quickbox-ws
```

**Comment by Velenski** [comment]
> Reinstall dependencies by following command
> 
> ```shell
> cd /srv/dashboard/ws/
> npm ci --production
> # check result
> /usr/bin/node /srv/dashboard/ws/dist/server.js
> # if start successfully
> systemctl restart quickbox-ws
> ```

-bash: npm: command not found

tried different abriviations of that but nothing

**Comment by Velenski** [comment]
![image](https://github.com/amefs/quickbox-lite/assets/54041984/76218c40-7e2e-44fe-9e8e-4efd8b7d3705)

**Comment by tautcony** [comment]
> > Reinstall dependencies by following command
> > ```shell
> > cd /srv/dashboard/ws/
> > npm ci --production
> > # check result
> > /usr/bin/node /srv/dashboard/ws/dist/server.js
> > # if start successfully
> > systemctl restart quickbox-ws
> > ```
> 
> -bash: npm: command not found
> 
> tried different abriviations of that but nothing

Okay, I know what the problem is.

please reinstall nodejs and re-execute the previous set of commands.

```shell
apt-get remove -y nodejs
curl -fsSL https://deb.nodesource.com/setup_18.x | bash - &&\
apt-get install -y nodejs
```

**Comment by Velenski** [comment]
> > > Reinstall dependencies by following command
> > > ```shell
> > > cd /srv/dashboard/ws/
> > > npm ci --production
> > > # check result
> > > /usr/bin/node /srv/dashboard/ws/dist/server.js
> > > # if start successfully
> > > systemctl restart quickbox-ws
> > > ```
> > 
> > 
> > -bash: npm: command not found
> > tried different abriviations of that but nothing
> 
> Okay, I know what the problem is.
> 
> please reinstall nodejs and re-execute the previous set of commands(The npm should exists).
> 
> ```shell
> apt-get remove -y nodejs
> curl -fsSL https://deb.nodesource.com/setup_18.x | bash - &&\
> apt-get install -y nodejs
> ```

yes this fixed it.
had to remove dpkg locks when done but that was easy with the fix
i assume the fix is implemented in the code for fresh installs?
i am planning on installing quite a few of these lol

**Comment by tautcony** [comment]
Yes, the fresh install script need a few fixes

**Comment by Velenski** [comment]
> ```shell
> ```shell
> systemctl restart quickbox-ws
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

fantastic
we well await the fixes then, won't be installing anything before next week anyway  :)
thanks for the help

**Comment by Popol069** [comment]
Hi, 
just for information, when are you going to modify the script?

Regards,

P.

**Comment by tautcony** [comment]
Change has been pushed to `development` branch, will be merged into `master` after more testing.

**Comment by Popol069** [comment]
Hello,

Thanks, 

So I can test with --dev ?

Regards,

**Comment by tautcony** [comment]
> Hello,
> 
> 
> 
> Thanks, 
> 
> 
> 
> So I can test with --dev ?
> 
> 
> 
> Regards,

Yes.
