### ISSUE TITLE
fio script not work

### ISSUE THREAD

**Issue by SnAFKe** [amefs/quickbox-lite#79]
When i try to use fio-bench.py return this error.

```
Traceback (most recent call last):
  File "/usr/local/bin/quickbox/system/auxiliary/fio-bench.py", line 9, in <module>
    from prettytable import PrettyTable
ImportError: No module named prettytable
```

Module prettytable seems missing

```ssh
# python3 -m pip freeze | grep prettytable
```

**Comment by amefs** [comment]
You can manually install by executing `python3 -m pip install prettytable`. It will be fixed in the next release.

**Comment by SnAFKe** [comment]
Not work.

```
# python3 -m pip install prettytable
Collecting prettytable
  Downloading https://files.pythonhosted.org/packages/94/d5/52e48f3bcf66f838d411ad85c3ac9550c2451d082623e2d4d4df7411ed5c/prettytable-2.0.0-py3-none-any.whl
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from prettytable) (40.8.0)
Collecting wcwidth (from prettytable)
  Downloading https://files.pythonhosted.org/packages/59/7c/e39aca596badaf1b78e8f547c807b04dae603a433d3e7a7e04d67f2ef3e5/wcwidth-0.2.5-py2.py3-none-any.whl
Installing collected packages: wcwidth, prettytable
Successfully installed prettytable-2.0.0 wcwidth-0.2.5
# fio-bench.py
Traceback (most recent call last):
  File "/usr/local/bin/quickbox/system/auxiliary/fio-bench.py", line 9, in <module>
    from prettytable import PrettyTable
ImportError: No module named prettytable
```

**Comment by amefs** [comment]
alright, just wait a moment. I need some time to push the new code here.

**Comment by amefs** [comment]
now, [switch to the development branch](https://en.wiki.ptbox.dev/getting-started/#already-have-quickbox-installed-and-want-to-switch-over-to-development) and try again pls.

**Comment by SnAFKe** [comment]
I not test your dev branch but i see the problem and i not sure if this your fix.

In fio-bench.py you declare `#!/usr/bin/env python` instead of `#!/usr/bin/env python3`

Because is old file that is why.

**Comment by amefs** [comment]
yep, I just port it to python3 last month.

**Comment by amefs** [comment]
now fix available in master branch
